/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package classes;

import java.awt.Font;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.plaf.ColorUIResource;
import javax.swing.plaf.FontUIResource;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author G50
 */
public class Employee extends javax.swing.JPanel {

    /**
     * Creates new form session_reporting
     */
    Connection con = null;
    ResultSet rs;
    Statement st;
    PreparedStatement pst = null;
    int test=3;
     

    public Employee() {
        initComponents();
        UIManager UI = new UIManager();
        UI.put("OptionPane.messageFont", new FontUIResource(new Font("Trebuchet MS", 1, 15)));
        UI.put("OptionPane.background", new ColorUIResource(255, 255, 255));
        UI.put("Panel.background", new ColorUIResource(255, 255, 255));
        try {
            String dbname = "ems";
            String pass = "password";
            String username = "root";
            String Url = "jdbc:mysql://localhost:3306/";
            String Drivers = "com.mysql.jdbc.Driver";

            Class.forName(Drivers);
            con = DriverManager.getConnection(Url + dbname, username, pass);           

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Connection to database unsuccesful", "Alert", 1);
            System.exit(0);
        }
        
        
            DefaultTableModel model = new DefaultTableModel();
        try {
            model = (DefaultTableModel) eTable.getModel();

            String sql2 = "SELECT * FROM employee ";
            st = con.createStatement();
            rs = st.executeQuery(sql2);
            model.setRowCount(0);
            while (rs.next()) {
                String emp_no = rs.getString("employee_number");
                String name = rs.getString("name");
                String id_number = rs.getString("id_number");
                String department = rs.getString("department");
                

                model.addRow(new Object[]{emp_no, name, id_number, department});

            }
        } catch (Exception e) {
         JOptionPane.showMessageDialog(null, e, "Alert", 1);
        }
        
       
        
        String id=(model.getValueAt(0, 0).toString());
        
        try {
            String sql2 = "SELECT * FROM employee ";
            st = con.createStatement();
            rs = st.executeQuery(sql2);
            
            while (rs.next()) {
                if(id.equals(rs.getString("employee_number"))){
              e1.setText(rs.getString("employee_number"));
                e2.setText( rs.getString("name"));
               e3.setSelectedItem(rs.getString("gender"));
               e4.setText(rs.getString("id_number"));
               e5.setText(rs.getString("phone_number"));
               e6.setText(rs.getString("physical_address"));
                String date = rs.getString("dob");
   java.util.Date date2 = new SimpleDateFormat("dd/mm/yyyy").parse(date);
   e7.setDate(date2);
               e8.setSelectedItem(rs.getString("department"));
                e9.setText(rs.getString("position"));
                e10.setText(rs.getString("responsibilities"));
               e11.setSelectedItem(rs.getString("bank"));
                e12.setText(rs.getString("branch"));
               e13.setText(rs.getString("acc_number"));
                e14.setText(rs.getString("gross_income"));
               e15.setText(rs.getString("kra_pin"));
                e16.setText(rs.getString("nssf_number"));
                e17.setText(rs.getString("nhif_number"));               
                break;
                }
            }
        } catch (Exception e) {
         JOptionPane.showMessageDialog(null, e, "Alert", 1);
        }

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        uL4 = new javax.swing.JLabel();
        uL11 = new javax.swing.JLabel();
        e9 = new javax.swing.JTextField();
        uL12 = new javax.swing.JLabel();
        e8 = new javax.swing.JComboBox<String>();
        jScrollPane1 = new javax.swing.JScrollPane();
        e10 = new javax.swing.JTextArea();
        lB4 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        e2 = new javax.swing.JTextField();
        bl = new javax.swing.JLabel();
        e1 = new javax.swing.JTextField();
        uL10 = new javax.swing.JLabel();
        bl4 = new javax.swing.JLabel();
        bl5 = new javax.swing.JLabel();
        e4 = new javax.swing.JTextField();
        bl7 = new javax.swing.JLabel();
        e6 = new javax.swing.JTextField();
        bl10 = new javax.swing.JLabel();
        e3 = new javax.swing.JComboBox<String>();
        e5 = new javax.swing.JTextField();
        bl12 = new javax.swing.JLabel();
        e7 = new com.toedter.calendar.JDateChooser();
        jPanel4 = new javax.swing.JPanel();
        uL9 = new javax.swing.JLabel();
        uL13 = new javax.swing.JLabel();
        e12 = new javax.swing.JTextField();
        e11 = new javax.swing.JComboBox<String>();
        e13 = new javax.swing.JTextField();
        uL15 = new javax.swing.JLabel();
        e15 = new javax.swing.JTextField();
        uL16 = new javax.swing.JLabel();
        e16 = new javax.swing.JTextField();
        uL17 = new javax.swing.JLabel();
        e17 = new javax.swing.JTextField();
        uL18 = new javax.swing.JLabel();
        e14 = new javax.swing.JTextField();
        uL19 = new javax.swing.JLabel();
        lB7 = new javax.swing.JButton();
        lB6 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        eTable = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1142, 560));
        setPreferredSize(new java.awt.Dimension(1142, 560));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Job Details  ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Trebuchet MS", 0, 18))); // NOI18N
        jPanel3.setOpaque(false);
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        uL4.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        uL4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        uL4.setText("Department");
        jPanel3.add(uL4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 140, 30));

        uL11.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        uL11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        uL11.setText("Position");
        jPanel3.add(uL11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 140, 30));

        e9.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        e9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel3.add(e9, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 240, 30));

        uL12.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        uL12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        uL12.setText("Responsibilities");
        jPanel3.add(uL12, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 130, 30));

        e8.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        e8.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ICT", "Finance", "Security", "Production", "Public Relations", "Sales & Marketing", "Maintenance", "HR" }));
        e8.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                e8ItemStateChanged(evt);
            }
        });
        jPanel3.add(e8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 240, 30));

        e10.setColumns(20);
        e10.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        e10.setRows(4);
        jScrollPane1.setViewportView(e10);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 400, 80));

        lB4.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lB4.setText("Delete");
        lB4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lB4ActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Personal Details   ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Trebuchet MS", 0, 18))); // NOI18N
        jPanel2.setOpaque(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        e2.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        e2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(e2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 280, 30));

        bl.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        bl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        bl.setText("Name");
        jPanel2.add(bl, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 110, 20));

        e1.setEditable(false);
        e1.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        e1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(e1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 280, -1));

        uL10.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        uL10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        uL10.setText("Emp_no ");
        jPanel2.add(uL10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 90, 20));

        bl4.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        bl4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        bl4.setText("Gender");
        jPanel2.add(bl4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 110, 30));

        bl5.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        bl5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        bl5.setText("ID_number");
        jPanel2.add(bl5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 110, 20));

        e4.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        e4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(e4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 280, 30));

        bl7.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        bl7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        bl7.setText("Physical Addrs");
        jPanel2.add(bl7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 140, 20));

        e6.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        e6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(e6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 280, 30));

        bl10.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        bl10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        bl10.setText("Date of Birth");
        jPanel2.add(bl10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 140, 20));

        e3.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        e3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Male", "Female" }));
        e3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                e3ItemStateChanged(evt);
            }
        });
        jPanel2.add(e3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 280, 30));

        e5.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        e5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(e5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 280, 30));

        bl12.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        bl12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        bl12.setText("Phone Number");
        jPanel2.add(bl12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 140, 20));

        e7.setDateFormatString("dd/mm/yyyy");
        e7.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jPanel2.add(e7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 280, 30));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Financial Details  ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Trebuchet MS", 0, 18))); // NOI18N
        jPanel4.setOpaque(false);
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        uL9.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        uL9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        uL9.setText("Bank");
        jPanel4.add(uL9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 60, 30));

        uL13.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        uL13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        uL13.setText("Branch");
        jPanel4.add(uL13, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 70, 30));

        e12.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        e12.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel4.add(e12, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 240, 30));

        e11.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        e11.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cooperative", "Equity", "Barclays", "National", "KCB" }));
        e11.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                e11ItemStateChanged(evt);
            }
        });
        jPanel4.add(e11, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 240, 30));

        e13.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        e13.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel4.add(e13, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 240, 30));

        uL15.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        uL15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        uL15.setText("Acc. No");
        jPanel4.add(uL15, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 80, 30));

        e15.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        e15.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel4.add(e15, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 240, 30));

        uL16.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        uL16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        uL16.setText("Kra Pin");
        jPanel4.add(uL16, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 80, 30));

        e16.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        e16.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel4.add(e16, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 240, 30));

        uL17.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        uL17.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        uL17.setText("Nssf. No");
        jPanel4.add(uL17, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 80, 30));

        e17.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        e17.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        e17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e17ActionPerformed(evt);
            }
        });
        jPanel4.add(e17, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 240, 30));

        uL18.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        uL18.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        uL18.setText("Nhif. No");
        jPanel4.add(uL18, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 80, 30));

        e14.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        e14.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel4.add(e14, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 240, 30));

        uL19.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        uL19.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        uL19.setText("Gross Income");
        jPanel4.add(uL19, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 110, 30));

        lB7.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lB7.setText("Add New");
        lB7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lB7ActionPerformed(evt);
            }
        });

        lB6.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lB6.setText("Update");
        lB6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lB6ActionPerformed(evt);
            }
        });

        eTable.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        eTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Emp_no", "Name", "ID Number", "Department"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        eTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(eTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lB7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lB4, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                            .addComponent(lB6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(58, 58, 58))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(11, 11, 11))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addComponent(lB7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lB6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lB4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lB4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lB4ActionPerformed
if(test!=2){
        
        String ID = e1.getText();
        try {
            String sql = "delete from employee where employee_number='" + ID + "'";

            pst = con.prepareStatement(sql);
            pst.execute();
              e1.setText("");
        e2.setText("");
        e4.setText("");
        e5.setText("");
        e6.setText("");      
        e9.setText("");
        e10.setText("");
        e12.setText("");
        e13.setText("");
        e14.setText("");
        e15.setText("");
        e16.setText("");
        e17.setText("");
         DefaultTableModel model = new DefaultTableModel();
        try {
            model = (DefaultTableModel) eTable.getModel();

            String sql2 = "SELECT * FROM employee ";
            st = con.createStatement();
            rs = st.executeQuery(sql2);
            model.setRowCount(0);
            while (rs.next()) {
                String emp_no = rs.getString("employee_number");
                String name = rs.getString("name");
                String id_number = rs.getString("id_number");
                String department = rs.getString("department");
                

                model.addRow(new Object[]{emp_no, name, id_number, department});

            }
        } catch (Exception e) {
         JOptionPane.showMessageDialog(null, e, "Alert", 1);
        }
            JOptionPane.showMessageDialog(this, "Operation  Succesful", "Alert", 1);
            
            
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e, "Alert", 1);
        }
}else{
     test=3;
 lB6.setVisible(true);
    lB7.setText("Add New");
      lB4.setText("Delete");
DefaultTableModel model = new DefaultTableModel();
 model = (DefaultTableModel) eTable.getModel();
    String id=(model.getValueAt(0, 0).toString());
        
        try {
            String sql2 = "SELECT * FROM employee ";
            st = con.createStatement();
            rs = st.executeQuery(sql2);
            
            while (rs.next()) {
                if(id.equals(rs.getString("employee_number"))){
              e1.setText(rs.getString("employee_number"));
                e2.setText( rs.getString("name"));
               e3.setSelectedItem(rs.getString("gender"));
               e4.setText(rs.getString("id_number"));
               e5.setText(rs.getString("phone_number"));
               e6.setText(rs.getString("physical_address"));
                String date = rs.getString("dob");
   java.util.Date date2 = new SimpleDateFormat("dd/mm/yyyy").parse(date);
   e7.setDate(date2);
               e8.setSelectedItem(rs.getString("department"));
                e9.setText(rs.getString("position"));
                e10.setText(rs.getString("responsibilities"));
               e11.setSelectedItem(rs.getString("bank"));
                e12.setText(rs.getString("branch"));
               e13.setText(rs.getString("acc_number"));
                e14.setText(rs.getString("gross_income"));
               e15.setText(rs.getString("kra_pin"));
                e16.setText(rs.getString("nssf_number"));
                e17.setText(rs.getString("nhif_number"));               
                break;
                }
            }
        } catch (Exception e) {
         JOptionPane.showMessageDialog(null, e, "Alert", 1);
        }

    
}
        // TODO add your handling code here:
    }//GEN-LAST:event_lB4ActionPerformed

    private void e8ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_e8ItemStateChanged
        
        // TODO add your handling code here:
    }//GEN-LAST:event_e8ItemStateChanged

    private void e3ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_e3ItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_e3ItemStateChanged

    private void e11ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_e11ItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_e11ItemStateChanged

    private void lB7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lB7ActionPerformed
if (test==3){
    lB7.setText("Save");
    lB6.setVisible(false);
    lB4.setText("Cancel");
    test=2;
        e1.setText("");
        e2.setText("");
        e4.setText("");
        e5.setText("");
        e6.setText("");
        e9.setText("");
        e10.setText("");
        e12.setText("");
        e13.setText("");
        e14.setText("");
        e15.setText("");
        e16.setText("");
        e17.setText("");
}else{
    
  String name = e2.getText();
        String gender = (String) e3.getSelectedItem();
        String id_number = e4.getText();
        String phone_number = e5.getText();
        String physical_address = e6.getText();
       
        SimpleDateFormat sdf = new SimpleDateFormat("dd/mm/yyyy", Locale.getDefault());
     String dob = sdf.format(e7.getDate());       
        String department = (String) e8.getSelectedItem();
        String position = e9.getText();
        String responsibilities = e10.getText();
        String bank = (String) e11.getSelectedItem();
        String branch = e12.getText();
        String acc_number = e13.getText();
        String gross_income = e14.getText();
        String kra_pin = e15.getText();
        String nssf_number = e16.getText();
        String nhif_number = e17.getText();
        

        if (name.equals("") || id_number.equals("") || phone_number.equals("") || physical_address.equals("")||
            dob.equals("") || department.equals("") || position.equals("") || responsibilities.equals("") ||
                bank.equals("") || branch.equals("") || acc_number.equals("") || gross_income.equals("")||
                kra_pin.equals("") || nssf_number.equals("") || nhif_number.equals("")
                ) {
            JOptionPane.showMessageDialog(this, "Kindly fill all fields", "Alert", 1);
        } else {
            test=3;
    lB7.setText("Add New");
     lB6.setVisible(true);
      lB4.setText("Delete");
            try {

                String sql5 = "INSERT INTO employee(name,gender,id_number,phone_number,physical_address, dob,department,position,responsibilities,bank,branch,acc_number,gross_income,kra_pin,nssf_number,nhif_number)"
                        + "VALUES('" + name + "','" + gender + "','" + id_number + "','" + phone_number + "','" + physical_address + "','" + dob + "','" + department +"','" + position +"','" + responsibilities +"','" + bank +"','" + branch +"','" + acc_number +"','" + gross_income +"','" + kra_pin +"','" + nssf_number +"','" + nhif_number  +"')";
                pst = con.prepareStatement(sql5);
                pst.execute();
                 DefaultTableModel model = new DefaultTableModel();
        try {
            model = (DefaultTableModel) eTable.getModel();

            String sql2 = "SELECT * FROM employee ";
            st = con.createStatement();
            rs = st.executeQuery(sql2);
            model.setRowCount(0);
            while (rs.next()) {
                String emp_no = rs.getString("employee_number");
                String namex = rs.getString("name");
                String id_numberx = rs.getString("id_number");
                String departmenx = rs.getString("department");
                if(id_number.equals(id_numberx)){
                e1.setText(emp_no);
                }

                model.addRow(new Object[]{emp_no, namex, id_numberx, departmenx});

            }
        } catch (Exception e) {
         JOptionPane.showMessageDialog(null, e, "Alert", 1);
        }
                JOptionPane.showMessageDialog(this, "Employee Added Succesfully", "Alert", 1);

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e, "Alert", 1);
            }
        }
}
        // TODO add your handling code here:
    }//GEN-LAST:event_lB7ActionPerformed

    private void e17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_e17ActionPerformed

    private void lB6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lB6ActionPerformed
String name = e2.getText();
        String gender = (String) e3.getSelectedItem();
        String id_number = e4.getText();
        String phone_number = e5.getText();
        String physical_address = e6.getText();
        SimpleDateFormat sdf = new SimpleDateFormat("dd/mm/yyyy", Locale.getDefault());
     String dob = sdf.format(e7.getDate());   
        String department = (String) e8.getSelectedItem();
        String position = e9.getText();
        String responsibilities = e10.getText();
        String bank = (String) e11.getSelectedItem();
        String branch = e12.getText();
        String acc_number = e13.getText();
        String gross_income = e14.getText();
        String kra_pin = e15.getText();
        String nssf_number = e16.getText();
        String nhif_number = e17.getText();
        

        if (name.equals("") || id_number.equals("") || phone_number.equals("") || physical_address.equals("")||
            dob.equals("") || department.equals("") || position.equals("") || responsibilities.equals("") ||
                bank.equals("") || branch.equals("") || acc_number.equals("") || gross_income.equals("")||
                kra_pin.equals("") || nssf_number.equals("") || nhif_number.equals("")
                ) {
            JOptionPane.showMessageDialog(this, "Kindly fill all fields", "Alert", 1);
        } else {
            try {

                String sql = "Update employee set name='" + name + "',gender='" + gender + "',id_number='" + id_number + "',phone_number='" + phone_number +"',physical_address='" + physical_address +"',dob='" + dob + "',department='" + department +"',position='" + position +"',responsibilities='" + responsibilities +"',bank='" + bank +"',branch='" + branch +"',acc_number='" + acc_number +"',nssf_number='" + nssf_number +"',nhif_number='" + nhif_number +"' where employee_number='" + e1.getText() + "'";

            pst = con.prepareStatement(sql);
            pst.executeUpdate();
             DefaultTableModel model = new DefaultTableModel();
        try {
            model = (DefaultTableModel) eTable.getModel();

            String sql2 = "SELECT * FROM employee ";
            st = con.createStatement();
            rs = st.executeQuery(sql2);
            model.setRowCount(0);
            while (rs.next()) {
                String emp_no = rs.getString("employee_number");
                String namex = rs.getString("name");
                String id_numberx = rs.getString("id_number");
                String departmentx = rs.getString("department");
                

                model.addRow(new Object[]{emp_no, namex, id_numberx, departmentx});

            }
        } catch (Exception e) {
         JOptionPane.showMessageDialog(null, e, "Alert", 1);
        }
            JOptionPane.showMessageDialog(this, "Changes Saved Succesfully", "Alert", 1);                                     

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e, "Alert", 1);
            }
        }
        
// TODO add your handling code here:
    }//GEN-LAST:event_lB6ActionPerformed

    private void eTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eTableMouseClicked

        TableModel model=eTable.getModel();
        int row =eTable.getSelectedRow();
        String id=(model.getValueAt(row, 0).toString());
        
        try {
            String sql2 = "SELECT * FROM employee ";
            st = con.createStatement();
            rs = st.executeQuery(sql2);
            
            while (rs.next()) {
                if(id.equals(rs.getString("employee_number"))){
              e1.setText(rs.getString("employee_number"));
                e2.setText( rs.getString("name"));
               e3.setSelectedItem(rs.getString("gender"));
               e4.setText(rs.getString("id_number"));
               e5.setText(rs.getString("phone_number"));
               e6.setText(rs.getString("physical_address"));
              
             String date = rs.getString("dob");
   java.util.Date date2 = new SimpleDateFormat("dd/mm/yyyy").parse(date);
   e7.setDate(date2);
               
               e8.setSelectedItem(rs.getString("department"));
                e9.setText(rs.getString("position"));
                e10.setText(rs.getString("responsibilities"));
               e11.setSelectedItem(rs.getString("bank"));
                e12.setText(rs.getString("branch"));
               e13.setText(rs.getString("acc_number"));
                e14.setText(rs.getString("gross_income"));
               e15.setText(rs.getString("kra_pin"));
                e16.setText(rs.getString("nssf_number"));
                e17.setText(rs.getString("nhif_number"));
                
                test=3;
 lB6.setVisible(true);
    lB7.setText("Add New");
      lB4.setText("Delete");
                break;
                }
            }
        } catch (Exception e) {
         JOptionPane.showMessageDialog(null, e, "Alert", 1);
        }
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_eTableMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bl;
    private javax.swing.JLabel bl10;
    private javax.swing.JLabel bl12;
    private javax.swing.JLabel bl4;
    private javax.swing.JLabel bl5;
    private javax.swing.JLabel bl7;
    private javax.swing.JTextField e1;
    private javax.swing.JTextArea e10;
    private javax.swing.JComboBox<String> e11;
    private javax.swing.JTextField e12;
    private javax.swing.JTextField e13;
    private javax.swing.JTextField e14;
    private javax.swing.JTextField e15;
    private javax.swing.JTextField e16;
    private javax.swing.JTextField e17;
    private javax.swing.JTextField e2;
    private javax.swing.JComboBox<String> e3;
    private javax.swing.JTextField e4;
    private javax.swing.JTextField e5;
    private javax.swing.JTextField e6;
    private com.toedter.calendar.JDateChooser e7;
    private javax.swing.JComboBox<String> e8;
    private javax.swing.JTextField e9;
    private javax.swing.JTable eTable;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton lB4;
    private javax.swing.JButton lB6;
    private javax.swing.JButton lB7;
    private javax.swing.JLabel uL10;
    private javax.swing.JLabel uL11;
    private javax.swing.JLabel uL12;
    private javax.swing.JLabel uL13;
    private javax.swing.JLabel uL15;
    private javax.swing.JLabel uL16;
    private javax.swing.JLabel uL17;
    private javax.swing.JLabel uL18;
    private javax.swing.JLabel uL19;
    private javax.swing.JLabel uL4;
    private javax.swing.JLabel uL9;
    // End of variables declaration//GEN-END:variables
}
