/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package classes;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author G50
 */
public class loginWindow extends javax.swing.JFrame {

    /**
     * Creates new form loginMenu
     */
      Connection con = null;
    ResultSet rs;
    Statement st;
    PreparedStatement pst = null;
    
    public loginWindow() {
        initComponents();
           ImageIcon img = new ImageIcon(getClass().getResource("/resources/326.png"));
        this.setIconImage(img.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        uL1 = new javax.swing.JLabel();
        theUsername = new javax.swing.JTextField();
        pL1 = new javax.swing.JLabel();
        thePassword = new javax.swing.JPasswordField();
        lB1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login Menu");
        setMinimumSize(new java.awt.Dimension(400, 300));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLayeredPane1.setBackground(new java.awt.Color(255, 255, 255));
        jLayeredPane1.setOpaque(true);

        uL1.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        uL1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        uL1.setText("UserName");

        theUsername.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        theUsername.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        pL1.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        pL1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        pL1.setText("PassWord");

        thePassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        lB1.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lB1.setText("Log In");
        lB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lB1ActionPerformed(evt);
            }
        });

        jLayeredPane1.setLayer(uL1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(theUsername, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(pL1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(thePassword, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(lB1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(uL1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pL1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lB1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(thePassword, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(theUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(theUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(107, 107, 107))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(uL1)
                        .addGap(39, 39, 39)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pL1)
                            .addComponent(thePassword, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)))
                .addComponent(lB1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lB1ActionPerformed
 if(theUsername.getText().equals("")||thePassword.getText().equals("")){
 JOptionPane.showMessageDialog(null, "Please provide the userName and password", "Alert", 1);

}
else{
    String userName=theUsername.getText();
    String passWord=thePassword.getText();
    
     try {
                    String sql2 = "SELECT * FROM user ";
                    st = con.createStatement();
                    rs = st.executeQuery(sql2);
                    int xp=1;
                    while (rs.next()) {
                        String userN = rs.getString("username");
                        String passW = rs.getString("password");
                         String level = rs.getString("level");
                        if (userN.equals(userName) && passW.equals(passWord)) {
                           main_window eri = new main_window();
                            eri.theUser = level;
                           this.dispose();
                           eri.setVisible(true);
                            xp = 3;
                            break;

                        } 

                    }
                    if (xp == 1) {

                        JOptionPane.showMessageDialog(this, "Wrong username or password Combination", "Alert", 1);
                    }
                 

                } catch (Exception e) {

                }
    }      

        // TODO add your handling code here:
    }//GEN-LAST:event_lB1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
try {
                        String dbname = "ems";
                        String pass = "password";
                        String username = "root";
                        String Url = "jdbc:mysql://localhost:3306/";
                        String Drivers = "com.mysql.jdbc.Driver";

                        Class.forName(Drivers);
                        con = DriverManager.getConnection(Url + dbname, username, pass);
                        //JOptionPane.showMessageDialog(null, "Connection succesful", "Lericks Student Aid Alert", 1);

                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, "Connection to database unsuccesful", "Alert", 1);
                        System.exit(0);
                    }
       
                                     

        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loginWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loginWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loginWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loginWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loginWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JButton lB1;
    private javax.swing.JLabel pL1;
    private javax.swing.JPasswordField thePassword;
    private javax.swing.JTextField theUsername;
    private javax.swing.JLabel uL1;
    // End of variables declaration//GEN-END:variables
}
