/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package classes;

import java.awt.Font;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.plaf.ColorUIResource;
import javax.swing.plaf.FontUIResource;

/**
 *
 * @author G50
 */
public class reports extends javax.swing.JPanel {

    /**
     * Creates new form session_reporting
     */
    Connection con = null;
    ResultSet rs;
    Statement st;
    PreparedStatement pst = null;

    public reports() {
        initComponents();
        UIManager UI = new UIManager();
        UI.put("OptionPane.messageFont", new FontUIResource(new Font("Trebuchet MS", 1, 15)));
        UI.put("OptionPane.background", new ColorUIResource(255, 255, 255));
        UI.put("Panel.background", new ColorUIResource(255, 255, 255));
        try {
            String dbname = "ems";
            String pass = "password";
            String username = "root";
            String Url = "jdbc:mysql://localhost:3306/";
            String Drivers = "com.mysql.jdbc.Driver";

            Class.forName(Drivers);
            con = DriverManager.getConnection(Url + dbname, username, pass);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Connection to database unsuccesful", "Alert", 1);
            System.exit(0);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        lB5 = new javax.swing.JButton();
        e11 = new javax.swing.JComboBox<String>();
        uL20 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lB6 = new javax.swing.JButton();
        e12 = new javax.swing.JComboBox<String>();
        uL21 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        lB7 = new javax.swing.JButton();
        uL22 = new javax.swing.JLabel();
        e14 = new javax.swing.JComboBox<String>();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1142, 560));
        setPreferredSize(new java.awt.Dimension(1142, 560));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "     Employees    ", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Trebuchet MS", 0, 18))); // NOI18N
        jPanel3.setOpaque(false);
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lB5.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lB5.setText("Generate");
        lB5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lB5ActionPerformed(evt);
            }
        });
        jPanel3.add(lB5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 152, 40));

        e11.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        e11.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "All", "On Leave" }));
        e11.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                e11ItemStateChanged(evt);
            }
        });
        jPanel3.add(e11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 240, 30));

        uL20.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        uL20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        uL20.setText("Choose Category");
        jPanel3.add(uL20, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 140, 30));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "     Leave    ", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Trebuchet MS", 0, 18))); // NOI18N
        jPanel4.setOpaque(false);
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lB6.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lB6.setText("Generate");
        lB6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lB6ActionPerformed(evt);
            }
        });
        jPanel4.add(lB6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 152, 40));

        e12.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        e12.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "All", "Annual Leave", "Maternity Leave", "Other Leave" }));
        e12.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                e12ItemStateChanged(evt);
            }
        });
        jPanel4.add(e12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 240, 30));

        uL21.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        uL21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        uL21.setText("Choose Leave Type");
        jPanel4.add(uL21, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 190, 30));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "     Wages    ", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Trebuchet MS", 0, 18))); // NOI18N
        jPanel5.setOpaque(false);
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lB7.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lB7.setText("Generate");
        lB7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lB7ActionPerformed(evt);
            }
        });
        jPanel5.add(lB7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 152, 40));

        uL22.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        uL22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        uL22.setText("Choose Category");
        jPanel5.add(uL22, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 150, 30));

        e14.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        e14.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bank", "KRA", "NSSF", "NHIF" }));
        e14.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                e14ItemStateChanged(evt);
            }
        });
        jPanel5.add(e14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 240, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(189, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lB5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lB5ActionPerformed
        String name = "";
        String tagline = "";
        String address = "";
        String email = "";
        try {
            String sql2 = "SELECT * FROM company ";
            st = con.createStatement();
            rs = st.executeQuery(sql2);
            while (rs.next()) {
                name = rs.getString("name");
                tagline = rs.getString("tagline");
                address = rs.getString("address");
                email = rs.getString("email");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e, "Alert", 1);
        }

        String sel = (String) e11.getSelectedItem();
        switch (sel) {
            case "All":
                emp_report erc = new emp_report();
                erc.name = name;
                erc.tagline = tagline;
                erc.address = address;
                erc.email = email;
                erc.generate();
                break;
            case "On Leave":
                emp_on_leave_report ercx = new emp_on_leave_report();
                ercx.name = name;
                ercx.tagline = tagline;
                ercx.address = address;
                ercx.email = email;
                ercx.generate();
                break;
            default:

                break;
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_lB5ActionPerformed

    private void e11ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_e11ItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_e11ItemStateChanged

    private void lB6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lB6ActionPerformed
        String name = "";
        String tagline = "";
        String address = "";
        String email = "";
        try {
            String sql2 = "SELECT * FROM company ";
            st = con.createStatement();
            rs = st.executeQuery(sql2);
            while (rs.next()) {
                name = rs.getString("name");
                tagline = rs.getString("tagline");
                address = rs.getString("address");
                email = rs.getString("email");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e, "Alert", 1);
        }

        String sel = (String) e12.getSelectedItem();
        switch (sel) {
            case "All":
                emp_on_leave_report ercx = new emp_on_leave_report();
                ercx.name = name;
                ercx.tagline = tagline;
                ercx.address = address;
                ercx.email = email;
                ercx.generate();
                break;
            case "Annual Leave":
                annual_leave_report ercxl = new annual_leave_report();
                ercxl.name = name;
                ercxl.tagline = tagline;
                ercxl.address = address;
                ercxl.email = email;
                ercxl.generate();
                break;
            case "Maternity Leave":
                maternity_leave ercxv = new maternity_leave();
                ercxv.name = name;
                ercxv.tagline = tagline;
                ercxv.address = address;
                ercxv.email = email;
                ercxv.generate();
                break;
            case "Other Leave":
                other_leave_report ercxr = new other_leave_report();
                ercxr.name = name;
                ercxr.tagline = tagline;
                ercxr.address = address;
                ercxr.email = email;
                ercxr.generate();
                break;
            default:

                break;
        }        // TODO add your handling code here:
    }//GEN-LAST:event_lB6ActionPerformed

    private void e12ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_e12ItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_e12ItemStateChanged

    private void lB7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lB7ActionPerformed
        String name = "";
        String tagline = "";
        String address = "";
        String pin = "";
        String email = "";
        try {
            String sql2 = "SELECT * FROM company ";
            st = con.createStatement();
            rs = st.executeQuery(sql2);
            while (rs.next()) {
                name = rs.getString("name");
                tagline = rs.getString("tagline");
                address = rs.getString("address");
                email = rs.getString("email");
                pin = rs.getString("pin");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e, "Alert", 1);
        }

        String sel = (String) e14.getSelectedItem();
        switch (sel) {
            case "Bank":
                emp_wages ercx = new emp_wages();
                ercx.name = name;
                ercx.tagline = tagline;
                ercx.address = address;
                ercx.email = email;
                ercx.pin = pin;
                ercx.generate();
                break;
            case "KRA":
                kra_wages ercxlr = new kra_wages();
                ercxlr.name = name;
                ercxlr.tagline = tagline;
                ercxlr.address = address;
                ercxlr.email = email;
                ercxlr.pin = pin;
                ercxlr.generate();
                break;
            case "NSSF":
                nssf_report ercxlrn = new nssf_report();
                ercxlrn.name = name;
                ercxlrn.tagline = tagline;
                ercxlrn.address = address;
                ercxlrn.email = email;
                ercxlrn.pin = pin;
                ercxlrn.generate();
                break;
            case "NHIF":
               nhif_report ercxlrnf = new nhif_report();
                ercxlrnf.name = name;
                ercxlrnf.tagline = tagline;
                ercxlrnf.address = address;
                ercxlrnf.email = email;
                ercxlrnf.pin = pin;
                ercxlrnf.generate();
                break;
            default:

                break;
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_lB7ActionPerformed

    private void e14ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_e14ItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_e14ItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> e11;
    private javax.swing.JComboBox<String> e12;
    private javax.swing.JComboBox<String> e14;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JButton lB5;
    private javax.swing.JButton lB6;
    private javax.swing.JButton lB7;
    private javax.swing.JLabel uL20;
    private javax.swing.JLabel uL21;
    private javax.swing.JLabel uL22;
    // End of variables declaration//GEN-END:variables
}
